// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ-jRBMByIJxJ7vJ4TpFzybiJq7J5ieVA',
    appId: '1:939528349057:web:0be3df5354cfd6558eb480',
    messagingSenderId: '939528349057',
    projectId: 'basicapp-5ef6f',
    authDomain: 'basicapp-5ef6f.firebaseapp.com',
    storageBucket: 'basicapp-5ef6f.appspot.com',
    measurementId: 'G-VKC79NPJ95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXw0NXydlZfDzZpf7UjyXttaKXEGBj9tA',
    appId: '1:939528349057:android:a7d46a26ea6cc7208eb480',
    messagingSenderId: '939528349057',
    projectId: 'basicapp-5ef6f',
    storageBucket: 'basicapp-5ef6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFy329PNKjS1Dfui3EvwIvgmxjZYtz4iE',
    appId: '1:939528349057:ios:cb395901d21e426b8eb480',
    messagingSenderId: '939528349057',
    projectId: 'basicapp-5ef6f',
    storageBucket: 'basicapp-5ef6f.appspot.com',
    iosBundleId: 'com.example.simpleCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFy329PNKjS1Dfui3EvwIvgmxjZYtz4iE',
    appId: '1:939528349057:ios:dd1c2dfe90e028f58eb480',
    messagingSenderId: '939528349057',
    projectId: 'basicapp-5ef6f',
    storageBucket: 'basicapp-5ef6f.appspot.com',
    iosBundleId: 'com.example.simpleCrudApp.RunnerTests',
  );
}
